const pagePathMap: Record<string, string> = {
    Landing: '/',
    Dashboard: '/dashboard',
    About: '/about',
    Privacy: '/privacy',
    Terms: '/terms',
    Contact: '/contact',
    Changelog: '/changelog',
    Status: '/status',
    GuestService: '/guest-service',
    DataSecurity: '/data-security',
    Accessibility: '/accessibility',
    SLA: '/sla',
    // App pages (must match route paths in App.jsx)
    Bookings: '/Bookings',
    Leads: '/Leads',
    Messages: '/Messages',
    MultiCalendar: '/MultiCalendar',
    Settings: '/Settings',
    Subscription: '/Subscription',
    Billing: '/Billing',
    Invoices: '/Invoices',
    Payments: '/Payments',
    Reviews: '/Reviews',
    Cleaning: '/Cleaning',
    Automations: '/Automations',
    Integrations: '/Integrations',
    AIAssistant: '/AIAssistant',
    RevenueIntelligence: '/RevenueIntelligence',
    OwnerReports: '/OwnerReports',
    GuestJourney: '/GuestJourney',
    DynamicPricing: '/DynamicPricing',
    GuestPortal: '/GuestPortal',
    Contracts: '/Contracts',
    ExpenseTracker: '/ExpenseTracker',
    BookingDetail: '/BookingDetail',
    LeadDetail: '/LeadDetail',
};

export function createPageUrl(pageName: string) {
    return pagePathMap[pageName] ?? '/' + pageName.replace(/ /g, '-');
}